spring.application.name=SalesSavvy
server.port=9090
spring.datasource.url=jdbc:mysql://localhost:3306/salessavvy
spring.datasource.username=root
spring.datasource.password=system


#spring.security.enabled=false
spring.autoconfigure.exclude=org.springframework.boot.autoconfigured.security.servlet.SecurityAutoConfiguration

jwt.secret=maya-it-is-your-very-long-secure-secret-key-for-production-mayadeepakkale
#miliseconds
jwt.expiration=3600000 
#to see the queries which are going to be execute by the backend
spring.jpa.hibernate.ddl-auto=validate
